KTAS-5: Apply Raft for distributed tasks
2600hz/kazoo-tasks pull request #39
Opened 2023-07-19 13:13 UTC by dhuynh-Kazoo

Apply a new way to distribute task jobs by using `ra` implementation. 
The following ticket: https://2600hz-commercial.atlassian.net/browse/KTAS-5.

---
Adding Karl's comment:

> my intention with regards to Raft was to use it to elect a worker when there are multiple.  IE: on start up of each task use raft to determine if there is another worker already for that task and if stop/defer to it.  otherwise take leadership of that task via raft and execute
> [10:31](https://2600hz.slack.com/archives/D0535CAVDAT/p1693323113967149)
> you could take a look at how fax workers do the job distribution using raft to "lock" each account to a node when they pickup a new job
> [10:33](https://2600hz.slack.com/archives/D0535CAVDAT/p1693323223343529)
> for tasks they aren't necessarily as associated with accounts as faxes so we might need to lock at a different level, such as the task type, without looking into details I believe the best would be to acquire a raft leadership as a combination of task type and trigger (IE: task X running every Y) releasing each time that specific instance completes
> [10:35](https://2600hz.slack.com/archives/D0535CAVDAT/p1693323307316319)
> I would NOT want tasks to start up and get a raft lock for that instance, blocking all other tasks instances, as that would put every periodic task on one node and not be as robust as negotiating each trigger.
> 

---
update 04/23/2024.
[DRAFT] Summary about the implementation and question would need your answer/clarification:
- How do we start Erlang nodes in the cluster and how do they connect to each other to become a cluster?

- Summary for the idea(I'll update the detailed later). But it would be great if you can help me the review the idea. Thank you!! So Have all nodes connected then they can start an election, and then we have leader and followers. Most of the tasks are periodic type with gener_server behavior. So my idea is to send a start command for each type of task to the ra leader,  the leader starts the task on the random node and updates the task on it state _#{task_type => Type, node => node, pid => pid()}_. The leader will monitor the task and start it if crashes (choose a random node to start). 
Duplicated requests can be checked by ra leader by lookup the state with task type and pid on a node, if a duplicate is found, just rejects the command. Otherwise, implement that command

2023-07-24 14:52 UTC, dhuynh-Kazoo commented
hi @icehess, could you take the time to look at this PR?

I moved all sub-task modules to `task_ra_sup` and have only 4 functions for interaction with RA cluster: `start, stop, remove and sync_state`(for kz_tasks_scheduler because I noticed that only the scheduler needs to update to worker's state). So the ra server status is updated by the `tick/2`(spawn process every interval time to get `kz_tasks_scheduler` state ).

The other background tasks(some are time triggered and some are time interval set up) are independent and are not linked to `kz_task_scheduler`, so I just moved the worker processes from `task_sup` to my new `task_ra_sup`.

2023-07-28 16:18 UTC, jamesaimonetti requested changes
Some first checks

2023-07-28 16:18 UTC, jamesaimonetti commented on src/kz_tasks_scheduler.erl
> +        ,remove/1]).
revert this, project standards have these end-of-list  brackets dropped to newline

2023-07-28 16:18 UTC, jamesaimonetti commented on src/kz_account_crawler.erl
> +        ,crawl_account/1]).
drop end-of-list to newline

2023-07-28 16:18 UTC, jamesaimonetti commented on src/kz_account_crawler.erl
> +    _ = tasks_ra_action:pipeline_command({crawl_account, AccountId}),
ticky atoms

2023-07-28 16:18 UTC, jamesaimonetti commented on src/kz_notify_resend.erl
> +            ProcessingFun = fun () -> process_then_next_cycle([kz_json:get_value(<<"doc">>, J) || J <- Pendings]) end,
Can you change this to `kz_json:get_json_value` to use the typed accessor

2023-07-28 16:18 UTC, jamesaimonetti commented on src/kz_tasks_scheduler.erl
> +                                        ,[TaskId, API, ExtraArgs]}) of
drop `}` to newline, then `]` to a new line, then `of` to a line under that
```
    try tasks_ra_action:process_command({'spawn_link'
                                        ,fun Worker:start/3
                                        ,[TaskId, API, ExtraArgs]
                                        }
                                       )
    of
```

2023-07-28 16:18 UTC, jamesaimonetti commented on src/tasks_ra_action.erl
> +%%% @copyright (C) 2023, <COMPANY>
Fix header comment to match project standards

2023-07-28 16:18 UTC, jamesaimonetti commented on src/tasks_ra_action.erl
> +-author("dhuynh").
remove

2023-07-28 16:18 UTC, jamesaimonetti commented on src/tasks_ra_action.erl
> +        ,remove/1]).
drop end-of-list to newline

2023-07-28 16:18 UTC, jamesaimonetti commented on src/tasks_ra_node.erl
> +    Size = length(Nodes),
You might take the list of nodes and use kz_term:shuffle_list(Nodes) and hd() that

2023-08-02 08:04 UTC, dhuynh-Kazoo commented
Hi James, @jamesaimonetti changes with code format are updated

2023-08-16 13:52 UTC, dhuynh-Kazoo commented
Hi @jamesaimonetti and @icehess, could you help me with this concern? 
Because we have some workers with gen_server behavior in the tasks app, if we replicate them in all `ra` servers, it would cause duplication. So should we have a client node manages the requests and send them the `ra leader`, then `ra leader `will do the replication logic when ra servers execute?

2023-08-30 15:30 UTC, dhuynh-Kazoo commented
Hi @icehess and @jamesaimonetti, could you please review this pull request? I have made some changes for the ra_machine, workers are distributed in random node. When a function is called in a node, it will check if the server resides in current node, the execute it. Otherwise, check other nodes and use rpc call to execute it

2023-09-12 23:59 UTC, jamesaimonetti requested changes
Some quick checks

2023-09-12 23:59 UTC, jamesaimonetti commented on src/kt_number_crawler.erl
> +    case whereis(?MODULE) of
I don't understand this check. start_link + init suggest the server always starts, and tasks_sup has it as a child with no conditions.

Not sure why we'd want to stop remote crawlers too? Perhaps instead a `tasks_maintenance` command to stop the local server and one to stop remote servers too?

But if you can explain when we'd want to stop the server, that'd be helpful too.

2023-09-12 23:59 UTC, jamesaimonetti commented on src/kt_port_request_crawler.erl
> +    case whereis(?MODULE) of
Same questions here as for kt_number_crawler

2023-09-12 23:59 UTC, jamesaimonetti commented on src/kz_account_crawler.erl
> +    BinaryAccount =
I actually prefer to use function clauses for these. I think
```erlang
check(<<Account/binary>>) -> ...;
check(Account) ->
    check(kz_term:to_binary(Account)).
````

is more clear (as you know the first clause is working with a binary() and subsequent clauses do data transformation before the happy path clause

2023-09-12 23:59 UTC, jamesaimonetti commented on src/kz_account_crawler.erl
> +            case kz_datamgr:open_doc(?KZ_ACCOUNTS_DB, AccountId) of
Use `kzd_accounts:fetch/1`. The account doc in the account database is the authoritative doc; the account doc in the `accounts` database is not.

2023-09-12 23:59 UTC, jamesaimonetti commented on src/kz_notify_resend.erl
> +            case kz_datamgr:open_doc(?KZ_PENDING_NOTIFY_DB, Id) of
`kz_datamgr:open_cache_doc/2` should be used unless you have a good reason not to

2023-09-12 23:59 UTC, jamesaimonetti commented on src/kz_notify_resend.erl
> +                    kz_log:put_callid(kz_json:get_value(<<"payload">>, JObj)),
What is the expected value of `payload`? Use a kz_json typed accessor to match

2023-09-12 23:59 UTC, jamesaimonetti commented on src/tasks.hrl
> +-define(START_WORKER_RPC_CALL_TIMEOUT, 10 * ?MICROSECONDS_IN_SECOND).
Generally I like to see the time unit appended to the var name `START_WORKER_RPC_CALL_TIMEOUT_US` for microseconds here makes sense I think?

2023-09-12 23:59 UTC, jamesaimonetti commented on src/tasks_ra_node.erl
> +-define(TICK_INTERVAL, 20 * ?MILLISECONDS_IN_SECOND).
`TICK_INTERVAL_MS`

2023-09-12 23:59 UTC, jamesaimonetti commented on src/tasks_sup.erl
> +    {'ok', {SupFlags, []}}.
Oh, I see. You should probably remove the CHILDREN macro. The whereis checks make more sense now.

2023-09-14 02:41 UTC, dhuynh-Kazoo commented on src/kt_number_crawler.erl
> +    case whereis(?MODULE) of
Hi @jamesaimonetti, I have checked the task maintenance modules and other places so we do not use the `stop` functions. And they were added at the beginning when files were added. 

I think we can remove them since the task_sup manages the workers not using `stop`

2023-12-05 03:52 UTC, dhuynh-Kazoo commented on src/tasks_ra_node.erl
> +    case ra:start_server(RaConf) of
Hi @jamesaimonetti, these tasks_ra_* modules are replicated from `fax` app.

The idea of raft is that multiple nodes are connected and then vote for an election. I see an issue that may be a bug with the current implementation. When the `tasks` app starts, the code checks for connected nodes if no connected node, it becomes the leader. 

This is the race condition for the case that we have multiple erlang nodes, every node try to become the leader as they still not know others up and connected.

I think we have prefined cluster nodes in the configuration, when tasks app starts, it tries to connect each other with a timeout. If none of these nodes are found, it will become a leader. The cluster node will be set in the system_config db, please let me know your idea.

2023-12-05 03:52 UTC, dhuynh-Kazoo commented on src/kz_notify_resend.erl
> +                    kz_log:put_callid(kz_json:get_value(<<"payload">>, JObj)),
Hi Jame, I do not know the value of the payload because I do not have the case to test it in my local. Could you please give me an example of this? 

For ` Use a kz_json typed accessor to match` do you mean using a specific key?

2023-12-05 03:52 UTC, dhuynh-Kazoo commented on src/tasks_ra_node.erl
> +    case ra:start_server(RaConf) of
@icehess, please help to check and maybe share the way we used `ra` between erlang nodes in a cluster

2023-12-15 17:35 UTC, danielfinke commented on src/tasks_ra_node.erl
> +    case ra:start_server(RaConf) of
As I understand it, this is an inherent limitation of the Raft protocol or perhaps `ra`'s implementation of it. It is required that every node knows all cluster members ahead of time or at least that every node knows of a seed node that is started first: https://github.com/rabbitmq/ra/blob/main/docs/internals/INTERNALS.md#cluster-setup

2024-11-13 21:19 UTC, danielfinke commented on src/tasks_ra_node.erl
For `maybe_join`, `join`, `join_add_member`, and `start_new` take a look at what I have in this diff: https://github.com/2600hz/kazoo-qubicle/commit/155f9e6b448d3815bc6c5a76fdc43318da32bf93#diff-7c934d4272b6f4cb45840b352d92da59f1c969271593a1d918041e83eb345845. You'll see I have added a couple extra checks and I'm leaving lots of room for `badmatch` errors (intentionally). The idea is that if _any_ of these checks fail, the app should fail to start. Try those things out here.

Since Raft is strict about knowing the nodes ahead of time, the necessary deployment strategy for Ra apps is to make sure the Erlang nodes are connected to each other before the first start of the app. The cluster then forms successfully. For subsequent restarts, because the existing Ra server is restarted first, there is no need for the Erlang nodes to be connected. The Ra server will work fine once they are.

Decommissioning of a Ra app requires an explicit leave of the cluster (see my `leave_and_force_delete_server`).

2026-04-12 19:55 UTC, closed without merging