Added new tasks module to allow bulk creation of users.
2600hz/kazoo-tasks pull request #4
Opened 2020-05-25 19:52 UTC by bradfordben

2020-06-03 18:28 UTC, bradfordben commented
@jamesaimonetti Also when you have a sec can you look over this. It includes alot of changes you requested from the original PR i submitted a month back such as

- pulling required fields from the schema
- Using validation logic than has been moved out to kzd_users

Also added:
- pulling the optional fields from the setters in kzd_users and using the setters to build ontop of the default kad_users new doc

2020-06-12 21:04 UTC, jamesaimonetti requested changes
I would love to see a test added to kazoo-properly that shows the usage of this task. See for example the pqc_cb_rates module that uses the tasks API to upload the CSV of rates. In this case, I'd create the account, upload the users CSV, then query the users API (once the task is complete) to make sure all are created and have appropriate fields. A second test showing validation errors being returned for bad CSV data.

2020-06-12 21:04 UTC, jamesaimonetti commented on src/kz_tasks_utils.erl
> +            kz_doc:type(Doc) == DocType
Generally prefer strict equality `=:=` unless there's a good reason to use `==`.

2020-06-12 21:04 UTC, jamesaimonetti commented on src/kz_tasks_utils.erl
> +    ErrorBinaries = lists:map(fun(ValidationError) -> kazoo_doc_validation_error_to_binary(ValidationError) end
Can be `lists:map(fun kazoo_doc_validation_error_to_binary/1, ValidationErrors)`

2020-06-12 21:04 UTC, jamesaimonetti commented on src/kz_tasks_utils.erl
> +    PathBin = kz_term:to_binary(lists:join(".", Path)),
Could `kz_binary:join/2` work here instead?

2020-11-03 00:26 UTC, jamesaimonetti commented
@bradfordben what's your thought on this PR? Still relevant? Any progress on a kazoo-properly test?

2020-11-03 00:28 UTC, jamesaimonetti commented on src/kz_tasks_utils.erl
> +            kz_doc:type(Doc) == DocType
Also this could be `kz_datamgr:open_doc(AccountDb, {DocType, DocId})` to force the doc check at a lower level.

2020-11-03 17:58 UTC, bradfordben commented
Hey @jamesaimonetti, Yes it is still relevant, i just have not been given the time to build out a test mod for it unfortunately :( Sorry for the delay on this. I will make the other changes but for the tests i do not know when i will get a chance to build out.

2021-02-11 02:21 UTC, bradfordben commented
@jamesaimonetti I will get this and fix all the point you have raised.

2021-12-21 17:36 UTC, jamesaimonetti commented
@bradfordben what's the status here? I updated it to be in line with latest master. Do you have plans to address the comments? I think we can work together on this as there's interest in similar functionality. We're also looking at some funding for a general purpose onboarding task to take a CSV and create all the necessary connections between users, devices, callflows, etc.

Let me know!

2022-01-06 18:53 UTC, bradfordben commented
Hi @jamesaimonetti Sorry i just have been so busy with other tasks to get a chance to address your changes Thanks for reviewing. Il get to it this week. We would also like to see a CSV to objects type thing. We have a external tool right now that does it for creating accounts and objects within the account from a csv but we are always being asked for a more generic bulk creation tools from support

2026-04-12 19:55 UTC, closed without merging